# Generated by Django 5.0.7 on 2024-07-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_document_uploaded_at_alter_folder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
