# Generated by Django 5.1.1 on 2024-09-09 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_document_created_at_document_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaaSPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("max_storage_mb", models.IntegerField()),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("max_queries", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="document",
            name="embedding",
        ),
        migrations.AddField(
            model_name="document",
            name="cloudflare_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="FinanceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
                ("successful", models.BooleanField(default=True)),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[("credits", "Credits"), ("plan", "Plan")],
                        max_length=50,
                    ),
                ),
                (
                    "plan_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.saasplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "recharged_credits",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("plan_start_date", models.DateTimeField(blank=True, null=True)),
                ("plan_end_date", models.DateTimeField(blank=True, null=True)),
                ("is_plan_active", models.BooleanField(default=False)),
                ("total_documents_uploaded", models.IntegerField(default=0)),
                (
                    "saas_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.saasplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
