# Generated by Django 5.1.1 on 2024-09-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_saasplan_remove_document_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasplan",
            name="max_queries",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="saasplan",
            name="max_storage_mb",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="saasplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="saasplan",
            name="price_per_month",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
