# Generated by Django 5.1.1 on 2024-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_saasplan_max_queries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasplan",
            name="max_documents",
            field=models.IntegerField(default=0),
        ),
    ]
