# Generated by Django 5.1.1 on 2024-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_document_embeddings_stored_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
